.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. monedadelmundo_qt test_monedadelmundo_qt
clean: FORCE
	$(MAKE) -C .. monedadelmundo_qt_clean test_monedadelmundo_qt_clean
check: FORCE
	$(MAKE) -C .. test_monedadelmundo_qt_check
monedadelmundo-qt monedadelmundo-qt.exe: FORCE
	 $(MAKE) -C .. monedadelmundo_qt
apk: FORCE
	$(MAKE) -C .. monedadelmundo_qt_apk
